import { defineCollection, z } from 'astro:content';

// Note: 'slug' is auto-generated by Astro from filename, don't include in schema
// Use 'permalink' for custom URL paths if needed

const postsCollection = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    permalink: z.string().optional(), // Custom permalink if different from filename
    date: z.string(),
    updated: z.string().optional(),
    type: z.string().default('post'),
    status: z.string().default('publish'),
    excerpt: z.string().optional(),
    categories: z.array(z.string()).optional(),
    tags: z.array(z.string()).optional(),
    featuredImage: z.string().optional(),
    featuredImageAlt: z.string().optional(),
    authorId: z.number().optional(),
    readingTime: z.number().optional(),
    canonicalUrl: z.string().optional(),
  }),
});

const pagesCollection = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    permalink: z.string().optional(),
    date: z.string(),
    updated: z.string().optional(),
    type: z.string().default('page'),
    status: z.string().default('publish'),
    excerpt: z.string().optional(),
    featuredImage: z.string().optional(),
    featuredImageAlt: z.string().optional(),
    authorId: z.number().optional(),
    menuOrder: z.number().optional(),
    parentId: z.number().optional(),
    path: z.string().optional(),
    canonicalUrl: z.string().optional(),
  }),
});

const testimonialsCollection = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    permalink: z.string().optional(),
    date: z.string(),
    type: z.string(),
    status: z.string(),
    excerpt: z.string().optional(),
    featuredImage: z.string().optional(),
    featuredImageAlt: z.string().optional(),
    authorId: z.number().optional(),
    menuOrder: z.number().optional(),
    parentId: z.number().optional(),
    canonicalUrl: z.string().optional(),
  }),
});

const servicesCollection = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    permalink: z.string().optional(),
    date: z.string(),
    type: z.string(),
    status: z.string(),
    excerpt: z.string().optional(),
    featuredImage: z.string().optional(),
    featuredImageAlt: z.string().optional(),
    authorId: z.number().optional(),
    menuOrder: z.number().optional(),
    parentId: z.number().optional(),
    canonicalUrl: z.string().optional(),
  }),
});

const portfolioCollection = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    permalink: z.string().optional(),
    date: z.string(),
    type: z.string(),
    status: z.string(),
    excerpt: z.string().optional(),
    featuredImage: z.string().optional(),
    featuredImageAlt: z.string().optional(),
    authorId: z.number().optional(),
    menuOrder: z.number().optional(),
    parentId: z.number().optional(),
    canonicalUrl: z.string().optional(),
  }),
});

export const collections = {
  posts: postsCollection,
  pages: pagesCollection,
  testimonials: testimonialsCollection,
  service: servicesCollection,
  portfolio: portfolioCollection,
};
